<script setup lang="ts">
import { computed } from 'vue';
import { formatAmount, formatRate } from '@/utils/format-bridge';
interface Props { order: Api.RealFinance.OrderVO; }
const props = defineProps<Props>(); defineEmits<{ (event: 'redeem', order: Api.RealFinance.OrderVO): void }>();
const label = computed(() => props.order.statusText || ({ HOLDING: '计息中', REDEEMED: '已提前赎回', SETTLED: '已到期结算', CANCELED: '已取消' }[props.order.status] || ''));
const progress = computed(() => props.order.status === 'SETTLED' ? 100 : Math.min(100, Math.max(0, Math.round(((props.order.heldDays || 0) / props.order.lockDays) * 100))));
</script>
<template><view class="lockup-card"><view class="head"><view><text class="name">{{ order.productName }}</text><text class="code">#{{ order.productCode || order.id }}</text></view><wd-tag plain size="small">{{ label }}</wd-tag></view><view class="row"><view class="cell"><text class="lbl">本金</text><text class="val">U {{ formatAmount(order.principal) }}</text></view><view class="cell"><text class="lbl">年化</text><text class="val rate">{{ formatRate(Number(order.annualRate)) }}</text></view><view class="cell"><text class="lbl">已计收益</text><text class="val interest">+ U {{ formatAmount(order.accruedInterest) }}</text></view></view><wd-progress v-if="order.status === 'HOLDING' || order.status === 'SETTLED'" :percentage="progress" :color="order.status === 'SETTLED' ? '#00b42a' : '#722ed1'" /><text v-if="order.status === 'HOLDING'" class="progress-hint">已持有 {{ order.heldDays || 0 }}/{{ order.lockDays }} 天 · 剩余 {{ order.remainingDays || 0 }} 天</text><view v-if="order.canRedeem" class="actions"><wd-button type="error" plain size="small" @click="$emit('redeem', order)">提前赎回</wd-button></view></view></template>
<style lang="scss" scoped>.lockup-card { background:#fff; border-radius:16rpx; padding:24rpx; margin-bottom:16rpx; }.head { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:16rpx; padding-bottom:16rpx; border-bottom:1rpx dashed #f2f3f5; }.name { display:block; font-size:28rpx; font-weight:600; color:#1d2129; }.code { display:block; font-size:20rpx; color:#86909c; font-family:ui-monospace,monospace; }.row { display:flex; gap:16rpx; margin-bottom:16rpx; }.cell { flex:1; }.lbl { display:block; font-size:20rpx; color:#86909c; }.val { display:block; font-size:26rpx; font-weight:700; font-family:ui-monospace,monospace; color:#1d2129; margin-top:4rpx; }.val.rate { color:#722ed1; }.val.interest { color:#00b42a; }.progress-hint { display:block; font-size:20rpx; color:#4e5969; margin-top:8rpx; }.actions { display:flex; justify-content:flex-end; margin-top:16rpx; }</style>
